channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
- python=3.9
- seaborn
- scikit-learn
- statsmodels
- numba
- pytables
- python-igraph
- leidenalg
- graph-tool
- pip
- pytest
- tbb
- pip:
  - scanpy>=1.7.0
  - sc-dandelion
  - rpy2==3.4.2
  - git+https://github.com/zktuong/nxviz.git@custom_color_mapping_circos_nodes_and_edges
